language: python
python:
  - "3.6.9"

install:
  - pip install poetry
  - pip install coverage
  - pip install codecov
  - poetry install 
  
script: 
  - poetry run poe test
  - poetry run poe coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)